### ISSUE TITLE
Refactor: Organize Routes into Modules and Create Route Functions

### ISSUE THREAD

**Issue by Sidharth-Singh10** [Sidharth-Singh10/Affinity-backend#1]
**Description:**

As the number of routes in main.rs grows, it's essential to keep the file organized. 
We can split the routes into distinct modules and create functions that return Router instances for each group of routes. 
This approach maintains clarity and modularity without needing to handle routes as vectors.

**Tasks:**

**1.  Create Route Modules**

-  Organize routes into separate modules  based on functionality.

**2.    Define Grouped Routers in Each Module**

-  In each module, define a function that returns a `Router` with the relevant routes. 
-  For example, the auth_routes.rs module could define a function auth_routes() that returns a Router for login and signup     routes.

**3.    Merge Routes in main.rs**

-   In `main.rs` , call the functions from each module and nest them into the main Router using `.nest()` or by chaining them

**Benefits:**

-   Improved readability and modular structure.
-   Easier to maintain and add new routes as the application grows.
-   Logical grouping of routes based on their functionality.

References:
    [Axum Documentation](https://docs.rs/axum/latest/axum/)

**Comment by JonasBakys0** [comment]
Hi @Sidharth-Singh10, I would like to try to solve this issue if you don't mind.

**Comment by Sidharth-Singh10** [comment]
@JonasBakys0 Sure, go ahead!!
