### ISSUE TITLE
Missing `docker-compose.yml` File for Backend Setup

### ISSUE THREAD

**Issue by Sachin2815** [Sidharth-Singh10/Affinity-backend#15]
## Description

Hey! @Sidharth-Singh10 I noticed that the repository does not contain a `docker-compose.yml` file, which is essential for streamlining the setup of the backend services, particularly for the PostgreSQL database integration. 

 I have extensive experience in setting up Docker environments for both local development and production use. I've worked on several projects where `docker-compose` played a crucial role in streamlining the development process, and I am confident that I can deliver a high-quality solution for this repository.

 - The addition of a `docker-compose.yml` file would greatly improve the development and deployment process by enabling easier orchestration of the backend services using Docker. It can help set up both the Axum-based Rust backend and the PostgreSQL database seamlessly.

## Proposed Solution

I would like to contribute by adding a `docker-compose.yml` file that:

1. Defines services for the backend and PostgreSQL.
2. Configures networking to allow smooth communication between the backend and the database.
3. Includes relevant environment variables for database setup (e.g., username, password, database name).

This will allow contributors and developers to quickly spin up the backend environment using Docker, enhancing productivity and minimizing setup errors.

Please let me know if this sounds like a good enhancement, and I'd be happy to get started!

Thank you for your consideration! 😊

---

### Benefits:
- Easier setup and onboarding for new contributors.
- Simplified development environment with a single `docker-compose up` command.
- Enhanced alignment between local and production environments.

Looking forward to your feedback! 👨‍💻

**Comment by Sidharth-Singh10** [comment]
@Sachin2815, Thanks for the raising the issue!!
You can go ahead with your implementation.
Ping us if you need this issue labelled as `hacktoberfest` or `gssoc-ext`

**Comment by Sachin2815** [comment]
@Sidharth-Singh10 Yes! I am in Hacktoberfest and Gssoc-ext so label accordingly
