### ISSUE TITLE
 Add Local PostgreSQL Database Deployment in Helm Charts

### ISSUE THREAD

**Issue by Sidharth-Singh10** [Sidharth-Singh10/Affinity-backend#18]
**Description:**
I would like to request the addition of a local PostgreSQL database deployment in the Helm charts.
This would simplify local development and testing by ensuring that developers can spin up both the back-end and the database within the same Kubernetes cluster.

**Proposed Solution:**
-    Add a PostgreSQL deployment and service YAML definition to the existing Helm charts.
-    The database configuration (e.g., database name, user, password) should be managed via a ConfigMap or Secret.
-    Optionally, provide persistent storage using a PersistentVolumeClaim (PVC) for the database data.
 -   The PostgreSQL deployment should be configured to be easy to enable or disable based on whether a local PostgreSQL instance is required.

**Comment by SatyaD012** [comment]
@Sidharth-Singh10 Hello,
I'd like to work on this issue. Please assign it to me.
add labels gssoc-ext, hacktoberfest-accepted

**Comment by Sidharth-Singh10** [comment]
assigned!!

**Comment by yasheela-alla** [comment]
hello @Sidharth-Singh10 could you please assign this to me? i'd love to work on it.

**Comment by Sidharth-Singh10** [comment]
@yasheela-alla, @SatyaD012 has already opened up a PR.

**Comment by Aditya-PS-05** [comment]
@Sidharth-Singh10 ,
Can you assign this issue, as I have already encountered this issue during the local deployment.

**Comment by Sidharth-Singh10** [comment]
@Aditya-PS-05 , go ahead.

**Comment by aayushdhiman01** [comment]
@Sidharth-Singh10 I would like to work on this issue.
can you assign this to me.

**Comment by Sidharth-Singh10** [comment]
@aayushdhiman01, assigned

**Comment by mehul-m-prajapati** [comment]
@Sidharth-Singh10 : is any one working on this?

**Comment by Sidharth-Singh10** [comment]
@mehul-m-prajapati , the issue right now is internally being handled by the maintainers.
