### ISSUE TITLE
Security Issue: Token for Password Reset is Not Hashed Before Storing in Database

### ISSUE THREAD

**Issue by Sidharth-Singh10** [Sidharth-Singh10/Affinity-backend#21]
**Description:**

There is a potential security issue in the password reset process where the generated token for password reset is **not hashed** before being stored in the database. This exposes the token to anyone with access to the database, which could lead to unauthorized password resets if the token is compromised.

**Expected Behavior:**

The token should be hashed before being stored in the pass_reset table to ensure that even if the database is compromised, the token cannot be easily retrieved and misused.

Affected Code:
in `auth_handlers.rs`
   ```
 // The token is stored directly without hashing.
let pass_reset_model = pass_reset::ActiveModel {
    user_id: Set(user.id),
    token: Set(token),  // <--- This should be hashed before being stored.
    token_expiry: Set(token_expiry_timestamp),
    ..Default::default()
};
```

**Comment by Wahid7852** [comment]
what if we use bcrypt

**Comment by Wahid7852** [comment]
use bcrypt::{hash, verify, DEFAULT_COST};

// Hash the token before storing it
let hashed_token = hash(&token, DEFAULT_COST).expect("Failed to hash token");

let pass_reset_model = pass_reset::ActiveModel {
    user_id: Set(user.id),
    token: Set(hashed_token),  // Store the hashed token
    token_expiry: Set(token_expiry_timestamp),
    ..Default::default()
};

**Comment by Sidharth-Singh10** [comment]
Yes, we can do this but we are facing problem while trying to query the database.
The current model is defined as
```
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub token: String,
    pub token_expiry: i64,
}
```
While we store `hashed_token` into the database and the `unhashed_token` is sent user by email in the format `http://example/reset-password?token=xyz64digitrandom"`. 

- When a user submits the password reset request with the unhashed token `xyz64digitrandom`, the backend cannot hash it and compare it directly with the hashed token in the database because hashing the same token multiple times will produce different outputs due to salting.

- Querying all records from the  table and using `bcrypt::verify` for each record might work but is inefficient and doesn't scale well, especially with large datasets.

What do you think?

**Comment by Wahid7852** [comment]
what if we store the unhased token temporarily? 

Or even better if we use a Hashing Scheme like sha256, that'd be fixed but it'd be not recommended for passwords lol
maybe we set the token to expire after like 2-4 minutes?

like 

Generate Token
Send Email
Verify Submission
    If  matches, allow  reset.
    If not, query db and check  expiry timestamp.
Cleanup expired tokens

**Comment by Sidharth-Singh10** [comment]
SHA256 with expiry of 2-4 minutes might do the trick.
Been googling around for while, I am considering to use HMAC

- Generate a random token (xyz64digitrandom).
-  Generate an HMAC using a secret key, and store the signature (or HMAC) in the database instead of hashing the token.

When a user submits the token (xyz64digitrandom), the backend can:

-  Generate the signature (or HMAC) for the provided token using the same secret key.
-  Compare the generated signature (or HMAC) with the stored signature in the database.

**Comment by Wahid7852** [comment]
That'd work fine it seems, lmk if you need help

**Comment by ugochukwu-850** [comment]
What about using a TOTP

**Comment by Sidharth-Singh10** [comment]
afaik, TOTPs are used for  short times like 30s or 1min. 
Moreover, probably TOTPs doesn't fit our use case.

**Comment by ugochukwu-850** [comment]
@Sidharth-Singh10 
I am a little concerned as to why we even need to store password reset tokens , hashed or not - I am knew here btw so I might be getting some things wrong .
> Moreover, probably TOTPs doesn't fit our use case

And could I get a broader picture of the use case

**Comment by Sidharth-Singh10** [comment]
The reason we store password reset tokens (hashed or otherwise) is to securely identify and validate that a user who is trying to reset their password has clicked a valid link. Since the reset link is sent via email, it needs to be unique and bound to a particular user.
the token is attached to a link where they can enter their new password
`https://example.com/reset-password?token=xyz64digitrandomstring`

**Comment by Wahid7852** [comment]
TOTP would be out of scope for us and then complex enough
a simple hmacsha256 would be a great choice as pointed out by Sidhart

**Comment by Aditya-PS-05** [comment]
@Sidharth-Singh10 ,
Can you assign this task to me?

**Comment by Wahid7852** [comment]
> @Sidharth-Singh10 , Can you assign this task to me?

what is your approach

**Comment by Aditya-PS-05** [comment]
@Wahid7852 
I searched about it and found using HMAC with SHA256 approach most suitable.  I would generate an HMAC (Hash-based Message Authentication Code) with a secret key and this will allow me to verify the token without directly storing the unhashed version in the database

**Comment by Wahid7852** [comment]
@Sidharth-Singh10 check

**Comment by Sidharth-Singh10** [comment]
@Aditya-PS-05, assigned, you can work on it/

**Comment by Aditya-PS-05** [comment]
@Sidharth-Singh10 , 
I made the necessary changes. Please review it.
