### ISSUE TITLE
Update README.md to Improve Professionalism

### ISSUE THREAD

**Issue by rishyym0927** [Sidharth-Singh10/Affinity-backend#23]
The current README.md file lacks a professional structure and presentation, making it difficult for new contributors and users to understand the project. An updated README should provide clear, organized, and visually appealing information to reflect the quality of the project and enhance user engagement.

assign under gssoc hacktoberfest

**Comment by harshpareshbhaigosalya** [comment]
Hi @Sidharth-Singh10 
I can also do it, i have already perform for the [GTA5Chat](https://github.com/harshpareshbhaigosalya/GTA5Chat) repo you can check it out 
Assign this work to me i am eagerly waiting for your reply,
Thank you!
