### ISSUE TITLE
GSSOC EXT NOTICE: Improper Labeling in the Project

### ISSUE THREAD

**Issue by shreya-paul-17** [Sidharth-Singh10/Affinity-backend#26]
Dear Project Admin @Sidharth-Singh10 ,

It has come to our attention that your repository not applying the necessary labels to issues and merged PRs, which is affecting contributor scores on the leaderboard.

Please ensure you use the correct labels:

- gssoc-ext
- level1, level2, level3 
- hacktoberfest-accepted (only if your repository have Hacktoberfest topic in description)

*NOTE:* Level labels should not have any dashes between them. Spaces are allowed, but no dashes should be used.

Kindly review and update the labels on your issues and PRs to ensure fairness for all contributors. Failure to address this may result in your project being flagged.

Thank you,
Core Team
GSSoC '24 Extended

**Comment by ShashwatAgrawal20** [comment]
@shreya-paul-17 It's fixed now. Should I close the issue, or is it meant to remain?

**Comment by shreya-paul-17** [comment]
It's not done yet @ShashwatAgrawal20. Add level1, level2, level3 labels to the existing issues if assigned to the contributors along with the ones that have been merged already into the project. Also add hacktoberfest-accepted labels to the open issues and merged PRs both.
 After you do it, tag me once again and I'll check it to ensure if it is correct or not.

After that you can close this issue.

**Comment by ShashwatAgrawal20** [comment]
@shreya-paul-17 can you check once. 

LGTM! 

![shipit](https://github.com/user-attachments/assets/ad9bff95-6af4-4388-af2c-42575e61a226)

**Comment by Hemantlohar** [comment]
> @shreya-paul-17 can you check once.
> 
> LGTM!
> 
> ![shipit](https://private-user-images.githubusercontent.com/72117025/375052508-ad9bff95-6af4-4388-af2c-42575e61a226.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0OTIyMTMsIm5iZiI6MTcyODQ5MTkxMywicGF0aCI6Ii83MjExNzAyNS8zNzUwNTI1MDgtYWQ5YmZmOTUtNmFmNC00Mzg4LWFmMmMtNDI1NzVlNjFhMjI2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDE2MzgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxN2QyN2M4MzlkZmFiY2JkMDIyNzcwZDVjMzcxOWI3NDc1MmE3YzZiOGJlMjYzYmU4Y2RiZGM3YWFmN2E2NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Kt-gLjXG6TkDd66mr8vl2aW0MCOqGjieOC5CCQcIG6A) [ ![shipit](https://private-user-images.githubusercontent.com/72117025/375052508-ad9bff95-6af4-4388-af2c-42575e61a226.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0OTIyMTMsIm5iZiI6MTcyODQ5MTkxMywicGF0aCI6Ii83MjExNzAyNS8zNzUwNTI1MDgtYWQ5YmZmOTUtNmFmNC00Mzg4LWFmMmMtNDI1NzVlNjFhMjI2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDE2MzgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxN2QyN2M4MzlkZmFiY2JkMDIyNzcwZDVjMzcxOWI3NDc1MmE3YzZiOGJlMjYzYmU4Y2RiZGM3YWFmN2E2NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Kt-gLjXG6TkDd66mr8vl2aW0MCOqGjieOC5CCQcIG6A) ](https://private-user-images.githubusercontent.com/72117025/375052508-ad9bff95-6af4-4388-af2c-42575e61a226.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0OTIyMTMsIm5iZiI6MTcyODQ5MTkxMywicGF0aCI6Ii83MjExNzAyNS8zNzUwNTI1MDgtYWQ5YmZmOTUtNmFmNC00Mzg4LWFmMmMtNDI1NzVlNjFhMjI2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDE2MzgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxN2QyN2M4MzlkZmFiY2JkMDIyNzcwZDVjMzcxOWI3NDc1MmE3YzZiOGJlMjYzYmU4Y2RiZGM3YWFmN2E2NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Kt-gLjXG6TkDd66mr8vl2aW0MCOqGjieOC5CCQcIG6A) [ ](https://private-user-images.githubusercontent.com/72117025/375052508-ad9bff95-6af4-4388-af2c-42575e61a226.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0OTIyMTMsIm5iZiI6MTcyODQ5MTkxMywicGF0aCI6Ii83MjExNzAyNS8zNzUwNTI1MDgtYWQ5YmZmOTUtNmFmNC00Mzg4LWFmMmMtNDI1NzVlNjFhMjI2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDE2MzgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxN2QyN2M4MzlkZmFiY2JkMDIyNzcwZDVjMzcxOWI3NDc1MmE3YzZiOGJlMjYzYmU4Y2RiZGM3YWFmN2E2NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Kt-gLjXG6TkDd66mr8vl2aW0MCOqGjieOC5CCQcIG6A)

dlt this rn

**Comment by MastanSayyad** [comment]
Hi @ShashwatAgrawal20 

Discord is fine, but this is not how we react on a public platform, especially towards a member of the core team. She was referring to a situation from 2-3 days ago when some issues were open, and some contributors were complaining. 

The notice was initially given because this repo didn’t have the `hacktoberfest-accepted` label earlier, You can go ahead and close the issue. I can see that the labels have been fixed now. which is great


![image](https://github.com/user-attachments/assets/6602c3cb-5f1e-45c2-a85d-1990dfc30693)

**Comment by ShashwatAgrawal20** [comment]
Hey @MastanSayyad I understand your concern, that's just my saved replies template which I use to close every issue and PR, I didn't mean to disrespect anyone by anymeans. Sorry once again.
