### ISSUE TITLE
 Improve email_verfication.hbs file  to Match Website Color Scheme

### ISSUE THREAD

**Issue by Sidharth-Singh10** [Sidharth-Singh10/Affinity-backend#3]
## Description: 
The current email verification template uses a basic green and white color scheme, which may not align with the branding of the Affinity website. The template needs to be updated to match the website's color scheme and design elements for consistency.

## Current HTML: 
The email uses the following colors:
-    Header background: #4CAF50 (green)
-    Text color: #333 (gray)

## Expected Improvement:
-    Update the color scheme of the email to match the primary and secondary colors of the Affinity website.
-   Ensure that the header, OTP text, and button styles reflect the branding.
-  Maintain good readability and contrast across devices, following accessibility guidelines.

## For Reference
- Primary Color:`#F04B58`
- Secondary Color: `#272B2E`
- Background Color: `#000000`
- Text Color: `#FFFFFF`

**Comment by Seif-Mamdouh** [comment]
Hey @Sidharth-Singh10 can you assign this ticket to me! I can work on this

**Comment by Sidharth-Singh10** [comment]
Go ahead @Seif-Mamdouh.
Please attach a screenshot of rendered file in the PR

**Comment by Seif-Mamdouh** [comment]
hey @Sidharth-Singh10,

I'm running into a persistent database connection issue in your Rust backend application. 
<img width="1063" alt="Screenshot 2024-10-02 at 11 51 43 AM" src="https://github.com/user-attachments/assets/c0d475f3-bbb7-4248-86ef-e6b466e0e63d">

Here's a summary of the problem and the troubleshooting steps I've taken:
Issue: The application is failing to connect to the PostgreSQL database with the error message:
InvalidPort

Current setup:
The database (affinity_backend) exists and is accessible via `psql`.
The DATABASE_URL in the .env file appears to be correctly formatted.

Troubleshooting steps attempted:
- Verified the database exists using `psql -d affinity_backend`.
- Checked that the PostgreSQL port (5432) is correct in the connection string.
- Suggested adding debug logging to print the actual DATABASE_URL being used.
- Verified that the .env file is being properly loaded.

Please let me know how I can further diagnose this issue!

Or would be kind and give the steps on how to setup my local env file running?

**Comment by Sidharth-Singh10** [comment]
Hey @Seif-Mamdouh , I don't think it necessary for you to run the server to test the `.hbs` file.
To render the .hbs file, you can just copy its absolute path in your preferred browser.
Changes to made to html/css will be reflected accordingly. 

![image](https://github.com/user-attachments/assets/4e02b18c-6be9-4b61-a65d-77c40006365b)

**Comment by Seif-Mamdouh** [comment]
Hey @Sidharth-Singh10 thank for the clarification! I submitted a [PR](https://github.com/Sidharth-Singh10/Affinity-backend/pull/12)! Looking forward for the review!
