### ISSUE TITLE
Improve error handling for parse() in handlers

### ISSUE THREAD

**Issue by Sidharth-Singh10** [Sidharth-Singh10/Affinity-backend#4]
**Description:**

In both the` get_user_by_id_handler` and `update_contest_score_handler` functions, the code currently uses .parse().unwrap() to convert a string to an integer. However, using unwrap() can cause the application to panic if the string cannot be parsed. This should be improved by handling potential parse errors gracefully.

**Proposed Fix:**

Replace `.parse().unwrap()` with proper error handling that checks for the result of the `parse()` operation and returns an appropriate response (e.g., 400 Bad Request) if the parsing fails.

**Comment by HarshitShukla-dev** [comment]
Hey @Sidharth-Singh10 can you please assign this issue to me? I would love to work on this.

**Comment by Sidharth-Singh10** [comment]
@HarshitShukla-dev Go ahead!!

**Comment by HarshitShukla-dev** [comment]
Hey @Sidharth-Singh10 , it'll be very great of you if you add the gssoc-ext and a level label to my contribution as well.

**Comment by Sidharth-Singh10** [comment]
Done!!
Pick up some other issues if you are further interested to contribute into the project!!!

**Comment by HarshitShukla-dev** [comment]
> Done!! Pick up some other issues if you are further interested to contribute into the project!!!

Got you
