### ISSUE TITLE
Add the MIT License

### ISSUE THREAD

**Issue by Dipanita45** [Sidharth-Singh10/Affinity-backend#43]
License protect the project the website from the damage

Please assign to the issue 
@Sidharth-Singh10

**Comment by ShashwatAgrawal20** [comment]
hey @Dipanita45 this doesn't add any value to the project. 

Sorry,

![dontneedtoaddress](https://github.com/user-attachments/assets/893076b6-79b8-4f9c-97de-62db0c806401)


**CLOSING**

**Comment by ShashwatAgrawal20** [comment]
hey @Dipanita45 this doesn't add any value to the project.

Sorry,

![dontneedtoaddress](https://github.com/user-attachments/assets/83834099-cba2-4b55-b7cd-ccc6041875ca)


**CLOSING**
