### ISSUE TITLE
Redundant pattern matching - can be simplified using is_err() and is_some()

### ISSUE THREAD

**Issue by Sidharth-Singh10** [Sidharth-Singh10/Affinity-backend#5]
**Description:**
There are occurrences of redundant pattern matching in the code that can be simplified using more concise methods like` is_err()` and `is_some()` to improve readability and maintainability.

**Example 1: Simplifying Err(_) pattern matching**
Instead of:
`if let Err(_) = flag_update_result {
    // handle error
}`
We can use:
`
if flag_update_result.is_err() {
    // handle error
}
`

**Run** `cargo clippy` to see the warnings regarding this issue

**Comment by ghost** [comment]
Can u assign me this task?

**Comment by Sidharth-Singh10** [comment]
Assigned

**Comment by Aditya-PS-05** [comment]
@Sidharth-Singh10 ,
Can you assign this task to me?

**Comment by Wahid7852** [comment]
@Aditya-PS-05 it is still assigned to @oebelus
