### ISSUE TITLE
Add Issue Reminder Message Automation Workflow

### ISSUE THREAD

**Issue by amiya-cyber** [Sidharth-Singh10/Affinity-backend#53]
Description:
This workflow automatically checks for open issues that have been inactive for a set period and posts a reminder comment to prompt further action. It runs daily to help keep issues updated and ensure that unresolved items get attention.

ASSIGN THIS WITH LEVEL 3 LABEL @Sidharth-Singh10

**Comment by ShashwatAgrawal20** [comment]
Sorry,

![dontneedtoaddress](https://github.com/user-attachments/assets/a8f2c686-a552-40e1-8df7-5cd62d0f6da1)


**CLOSING**
