### ISSUE TITLE
Add "Back to Top" Scroll Button in README

### ISSUE THREAD

**Issue by tatheer-fathima** [Sidharth-Singh10/Affinity-backend#55]
Currently, the README file does not include a "Back to Top" button, making it difficult for users to navigate back to the beginning after scrolling through lengthy sections. Adding a "Back to Top" link at the end of the readme file will improve navigation, providing a better user experience for readers.

@Sidharth-Singh10 I would like to work on it.
Please assign it to me under gssoc-ext and hacktoberfest.

**Comment by ShashwatAgrawal20** [comment]
hey @T-Fathima, we're not here to entertain anyone, we don't need that so called back to top button on a README.

![dontneedtoaddress](https://github.com/user-attachments/assets/1947d952-ad50-4106-aafd-b05acbb4802a)

**CLOSING**
