### ISSUE TITLE
Adding a metrices table 

### ISSUE THREAD

**Issue by Aman-G-upta** [Sidharth-Singh10/Affinity-backend#56]
![Screenshot 2024-10-26 185138](https://github.com/user-attachments/assets/d2113ae9-46ca-4eb1-87c3-a23999c05e63)
Please assign me under this issue @Sidharth-Singh10

**Comment by ShashwatAgrawal20** [comment]
hey @Aman-G-upta, you should be making quality contributions dude and not these bullshit README issues. 

I also noticed you also created the exact same issue here also https://github.com/BhattAnsh/Quiz-Quest/issues/149

![stop-spamming](https://github.com/user-attachments/assets/0a2efb30-4667-4e0a-833c-7746621ba466)

**CLOSING**

**Comment by Aman-G-upta** [comment]
"Hello @ShashwatAgrawal20,

Thank you for your feedback, and I apologize for any inconvenience caused by my suggestion. My intention with adding a metrics table and program section was to provide a more structured overview for contributors and visitors. Metrics tables can help new contributors quickly understand the progress and impact of the repository, and a dedicated program section can clarify the purpose and goals of the project.

However, I understand your point about prioritizing quality contributions, and I’ll make sure to focus on more impactful enhancements going forward.

Thank you for your guidance!"
