### ISSUE TITLE
Add Automated Greeting Workflow

### ISSUE THREAD

**Issue by shubhagarwal1** [Sidharth-Singh10/Affinity-backend#9]
I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository. The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.
Hey @Sidharth-Singh10  please assign me this task

**Comment by Sidharth-Singh10** [comment]
assigned!!. Ping us if you want this issue to be labelled as `hacktoberfest` or `gssoc-ext`

**Comment by shubhagarwal1** [comment]
> assigned!!. Ping us if you want this issue to be labelled as `hacktoberfest` or `gssoc-ext`

yes please assign the labels 
gssoc-ext, hacktoberfest, level

**Comment by shubhagarwal1** [comment]
> > assigned!!. Ping us if you want this issue to be labelled as `hacktoberfest` or `gssoc-ext`
> 
> yes please assign the labels gssoc-ext, hacktoberfest, level @Sidharth-Singh10

**Comment by shubhagarwal1** [comment]
thank you starting working on it @Sidharth-Singh10

**Comment by ShashwatAgrawal20** [comment]
hey @shubhagarwal1 I don't think it's required.
